### ISSUE TITLE
User Preferences:

### ISSUE THREAD

**Issue by RlucSal** [kaiwright/projectOne#4]
Acceptance Criteria:
- [x]  Create a user-friendly profile page where users can set and update their preferences, which are stored using local storage.
- [x]  Use dropdowns, checkboxes, and sliders to capture various preferences.
- [x]  Save data as an object in local storage retrived as an array

**Comment by kaiwright** [comment]
User Story: 
As a user, I want to have a profile where my preferences are saved in a way that is easy to understand.
