### ISSUE TITLE
Recipe Retrieval (API #1):

### ISSUE THREAD

**Issue by RlucSal** [kaiwright/projectOne#6]
Acceptance Criteria:
- [x] Integrate with a recipe API like Spoonacular or Edamam using their provided endpoints.
- [x] Implement search functionality to allow users to find recipes based on keywords, ingredients, or cuisine types.
- [x] Fetch recipe details, including ingredients, instructions, and nutritional information

**Comment by kaiwright** [comment]
User Story: 
As a user, I want to have a wide variety of recipes suggested to me based on the food that I have and my preferences. I want to see details from the recipe to give me the information I will need to decide if I want to make it.
