### ISSUE TITLE
Chart.js implementation:

### ISSUE THREAD

**Issue by RlucSal** [kaiwright/projectOne#9]
Acceptance Criteria:
- [x] Integrate with chart.js to display data related to CO2 emissions in our recipes 
- [x] Develop calculation algorithms to convert CO2 emissions for recipes
- [x] Display the total carbon footprint for each recipe on the dashboard

**Comment by kaiwright** [comment]
User story:
As a user, I want to be able to use the calculator to see the carbon footprint of the recipes I am using.
